name: Deployments to Production
 
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [8.4]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json, dom, curl, libxml, mbstring, openssl
          coverage: none

      - name: Deploy Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            set -e
            cd /var/www/app
            git pull origin main
            export COMPOSER_ALLOW_SUPERUSER=1
            composer install --no-dev --no-progress --prefer-dist --optimize-autoloader
            npm install
            npm run build
            php artisan migrate --force
            php artisan optimize:clear
            php artisan config:cache
            php artisan route:cache
            sudo chown -R www-data:www-data /var/www/app
            sudo chmod -R 755 /var/www/app/storage /var/www/app/bootstrap/cache
            sudo systemctl restart php8.4-fpm
            sudo systemctl restart nginx