name: Deployments to Production
 
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [8.4]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json, dom, curl, libxml, mbstring, openssl
          coverage: none
      
      - name: Build Assets
        run: |
          npm install
          npm run build

      - name: Deploy to Server
        uses: wlixcc/SFTP-Deploy-Action@v1.2.5
        with:
          username: ${{ secrets.SSH_USER }}
          server: ${{ secrets.SSH_SERVER }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: './'
          remote_path: '/var/www/app'
          rsyncArgs: '--exclude=node_modules'
          sftpArgs: '-o ConnectTimeout=5'

      - name: Run SSH Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            set -e
            cd /var/www/app
            composer install --no-dev --no-progress --prefer-dist --optimize-autoloader
            sudo systemctl restart php8.4-fpm
            sudo systemctl restart nginx
            sudo chown -R www-data:www-data /var/www/app
            sudo chmod -R 755 /var/www/app/storage /var/www/app/bootstrap/cache